package io.github.aedev.flow.player.stream

import android.util.Log
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.SubtitlesStream

/** The timedtext form a caption track is fetched in, spelled as YouTube's `fmt` query value. */
enum class CaptionFormat(
    val fmtQueryValue: String,
) {
    SRV3("srv3"),
    VTT("vtt"),
}

/**
 * One caption track ready to fetch: a signed timedtext URL, or a `file:` URI for a track stored
 * beside a download.
 */
data class ResolvedCaption(
    val languageTag: String,
    val isAutoGenerated: Boolean,
    val url: String,
    val format: CaptionFormat,
) {
    val isTranslated: Boolean
        get() = url.contains("&${CaptionTrackResolver.TRANSLATED_PARAM}=")
}

private const val TAG = "ResolvedCaption"

/** The player still consumes NewPipe's stream type; this is the only place a caption becomes one. */
fun ResolvedCaption.toSubtitlesStream(): SubtitlesStream? =
    try {
        SubtitlesStream
            .Builder()
            .setContent(url, true)
            .setMediaFormat(
                when (format) {
                    CaptionFormat.SRV3 -> MediaFormat.TRANSCRIPT3
                    CaptionFormat.VTT -> MediaFormat.VTT
                },
            ).setLanguageCode(languageTag)
            .setAutoGenerated(isAutoGenerated)
            .build()
    } catch (e: Exception) {
        Log.w(TAG, "Failed to build SubtitlesStream for $languageTag: ${e.message}")
        null
    }

fun List<ResolvedCaption>.toSubtitlesStreams(): List<SubtitlesStream> = mapNotNull { it.toSubtitlesStream() }
