#!/usr/bin/env node
// Builds the Fathom string overlay for every locale from upstream's own translations.
//
//   node scripts/rebrand-strings.js           write app/src/fathom/res/values-*/strings.xml
//   node scripts/rebrand-strings.js --check   exit 1 if those files are out of date
//   node scripts/rebrand-strings.js --report  list "Flow" the script does not touch and nobody has decided on
//
// app/src/main/res/values*/strings.xml stay identical to upstream, so merging upstream never conflicts
// there. Fathom's own text lives in app/src/fathom/res, which the build lays over main:
//   fathom_strings.xml   written by hand: Fathom-only strings and fork-specific wording
//   strings.xml          generated here: upstream's translation with "Flow" turned into "Fathom"
// A key written by hand is never generated. Run this after every merge of upstream.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const MAIN = path.join(ROOT, 'app/src/main/res');
const FATHOM = path.join(ROOT, 'app/src/fathom/res');
const HAND = 'fathom_strings.xml';
const GENERATED = 'strings.xml';

// Translations upstream wrote with the app's name although the English text has none.
const EXTRA_KEYS = [
  'your_interests_desc',
  'sync_qr_network_note',
  'discord_presence_description',
  'discord_presence_gateway_warning',
  'learning_stats_subtitle',
  'style_default',
];

// Keys whose "Flow" stays on purpose (the engine, the original author, folder names on disk, the original theme).
// --report lists every other untouched "Flow", so a new upstream string is noticed instead of shipped as is.
const KEEP_KEYS = new Set([
  // the recommendation engine
  'auto_backup_type_brain',
  'deep_flow_active_until_disabled',
  'deep_flow_disabled_message',
  'deep_flow_enabled_message',
  'deep_flow_expired_message',
  'deep_flow_mode_title',
  'flow_neural_profile_export_subject',
  'import_engine_data',
  'import_engine_section_title',
  'pause_watch_history_subtitle',
  'settings_flow_engine_header',
  'settings_reset_brain_body',
  'settings_reset_brain_title',
  'tv_settings_flow_engine',
  // importing Flow backups, the folders Flow makes on disk, the original theme
  'import_flow_backup_desc',
  'import_flow_backup_failed_template',
  'import_flow_backup_item_title',
  'import_flow_backup_success',
  'location_downloads_label',
  'location_movies_label',
  'settings_music_folder_label',
  'theme_desc_classic_dark',
  'theme_name_classic_dark',
  // supporting and crediting the original author
  'settings_creator_role',
  'support_flow_dev_desc',
  'support_flow_dev_title',
  'support_flow_patreon',
]);

// Names of Flow's engine and other products stay as they are.
const KEEP = /^(?:\s*(?:Neuro|Engine|Brain|Personality|Neural|Desktop|Mode|Official|_))/;
const KEEP_BEFORE = /Deep $/;
const BRAND = /\b(Flow|FLOW)\b/g;

const ELEMENT = /<!--[\s\S]*?-->|<(string|plurals|string-array)\b[^>]*?(?:\/>|>[\s\S]*?<\/\1>)/g;

function read(file) {
  return fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : '';
}

function parse(text) {
  const entries = new Map();
  for (const match of text.matchAll(ELEMENT)) {
    if (match[0].startsWith('<!--')) continue;
    entries.set(/name="([^"]+)"/.exec(match[0])[1], match[0]);
  }
  return entries;
}

function isKept(text, index, word) {
  return KEEP.test(text.slice(index + word.length)) || KEEP_BEFORE.test(text.slice(0, index));
}

function hasBrand(text) {
  return [...text.matchAll(BRAND)].some((m) => !isKept(text, m.index, m[0]));
}

function rebrand(text) {
  return text.replace(BRAND, (word, _group, index) =>
    isKept(text, index, word) ? word : word === 'FLOW' ? 'FATHOM' : 'Fathom');
}

function render(entries) {
  const body = [...entries.values()].map((element) => `    ${element.trim()}\n`).join('');
  return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/rebrand-strings.js. Do not edit. -->\n<resources>\n${body}</resources>\n`;
}

const english = parse(read(path.join(MAIN, 'values/strings.xml')));
const fathomEnglish = parse(read(path.join(FATHOM, 'values', HAND)));
const rebranded = new Set(EXTRA_KEYS);
for (const [key, text] of fathomEnglish) {
  if (english.has(key) && hasBrand(english.get(key)) && !hasBrand(text)) rebranded.add(key);
}

const stale = [];
const locales = fs.readdirSync(MAIN).filter((d) => d.startsWith('values-') && fs.existsSync(path.join(MAIN, d, 'strings.xml')));
for (const locale of locales) {
  const upstream = parse(read(path.join(MAIN, locale, 'strings.xml')));
  const written = parse(read(path.join(FATHOM, locale, HAND)));
  const generated = new Map();
  for (const key of rebranded) {
    const text = upstream.get(key);
    if (text && !written.has(key) && hasBrand(text)) generated.set(key, rebrand(text));
  }
  const target = path.join(FATHOM, locale, GENERATED);
  const next = generated.size ? render(generated) : null;
  const current = fs.existsSync(target) ? read(target) : null;
  if (next === current) continue;
  stale.push(path.relative(ROOT, target));
  if (process.argv.includes('--check')) continue;
  if (next === null) fs.unlinkSync(target);
  else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, next);
  }
}

if (process.argv.includes('--check') && stale.length) {
  console.error(`Out of date, run node scripts/rebrand-strings.js:\n  ${stale.join('\n  ')}`);
  process.exit(1);
}
console.log(`${rebranded.size} keys rebranded across ${locales.length} locales, ${stale.length} files ${process.argv.includes('--check') ? 'stale' : 'updated'}.`);

if (process.argv.includes('--report')) {
  const decided = (key) => rebranded.has(key) || fathomEnglish.has(key) || KEEP_KEYS.has(key);
  const undecided = new Map();
  const skippedBy = new Map();
  const scan = (label, entries, handKeys) => {
    for (const [key, text] of entries) {
      if (decided(key) || handKeys.has(key)) continue;
      if (hasBrand(text)) undecided.set(`${label} ${key}`, text.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim().slice(0, 90));
    }
    for (const [, element] of entries) {
      const text = element.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ');
      for (const m of text.matchAll(BRAND)) {
        if (!isKept(text, m.index, m[0])) continue;
        const phrase = text.slice(Math.max(0, m.index - 5), m.index + m[0].length + 12).trim();
        skippedBy.set(phrase, (skippedBy.get(phrase) ?? 0) + 1);
      }
    }
  };
  scan('values', english, new Set());
  for (const locale of locales) {
    scan(locale, parse(read(path.join(MAIN, locale, 'strings.xml'))), parse(read(path.join(FATHOM, locale, HAND))));
  }
  console.log(`\nUndecided "Flow" (${undecided.size}): add the key to KEEP_KEYS, EXTRA_KEYS, or fathom_strings.xml`);
  for (const [where, text] of undecided) console.log(`  ${where}: ${text}`);
  const phrases = [...skippedBy].sort((a, b) => b[1] - a[1]).slice(0, 25);
  console.log(`\nLeft alone as product names (${skippedBy.size} distinct), most common:`);
  for (const [phrase, count] of phrases) console.log(`  ${String(count).padStart(4)}  ${phrase}`);
  if (undecided.size) process.exit(1);
}
