package io.github.aedev.flow.localserver

import io.github.aedev.flow.player.stream.serviceSupportsBulletComments
import org.schabi.newpipe.extractor.Page
import org.schabi.newpipe.extractor.comments.CommentsInfoItem
import org.schabi.newpipe.extractor.stream.Description
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamInfoItem

/**
 * The watch page (video and audio) and its comments. These pages carry no script of their own: the facts a script needs go out as a
 * JSON block (`#watch-config`, `#audio-config`), and js/player.js sets everything up from it.
 */
object HtmlRendererWatch {
    private fun formatChapterTimestamp(totalSeconds: Int): String {
        val h = totalSeconds / 3600
        val m = (totalSeconds % 3600) / 60
        val s = totalSeconds % 60
        return if (h > 0) "%d:%02d:%02d".format(h, m, s) else "%d:%02d".format(m, s)
    }

    /** The description as it goes into its box: plain text is escaped, HTML is left as it is, and stray blank lines at the ends dropped. */
    private fun descriptionHtml(info: StreamInfo): String {
        val description = info.description ?: return "No description provided."
        val content = description.content?.trim().orEmpty().ifEmpty { return "No description provided." }
        return if (description.type == Description.PLAIN_TEXT) WebUi.esc(content) else content
    }

    /** The related list, shared by the video page (opening videos) and the audio page (opening their audio). */
    private fun relatedList(
        info: StreamInfo,
        serviceId: Int,
        path: String,
    ): String {
        val sb = StringBuilder()
        for (related in info.relatedItems) {
            val stream = related as? StreamInfoItem
            val meta =
                if (stream != null) {
                    val views = if (stream.viewCount >= 0) "${HtmlRendererCommon.formatCount(stream.viewCount)} views" else "Live"
                    "$views • ${HtmlRendererCommon.formatUploadDate(stream.uploadDate, stream.textualUploadDate ?: "")}"
                } else {
                    ""
                }
            sb.append(
                WebUi.compactCard(
                    "$path?serviceId=$serviceId&id=${related.url}",
                    HtmlRendererCommon.getThumbnailUrl(related.thumbnailUrl),
                    related.name.orEmpty(),
                    stream?.uploaderName ?: related.name.orEmpty(),
                    meta,
                ),
            )
        }
        return sb.toString()
    }

    /** The page frame; the video itself arrives as a fragment (see [renderWatchContent]) so the page appears at once. */
    @JvmStatic
    fun renderWatchSkeleton(
        serviceId: Int,
        mediaUrl: String?,
        isTv: Boolean,
    ): String {
        val content =
            if (mediaUrl == null) {
                WebUi.notice("No video selected.", error = true)
            } else {
                WebUi.asyncRegion("/watch-content?serviceId=$serviceId&id=${WebUi.enc(mediaUrl)}", "Loading video streams...")
            }
        val body = WebShell.header(serviceId, "") + "<main class=\"container\">\n$content</main>\n"
        return WebShell.page("Loading video...", body, isTv, needsPlayer = true)
    }

    // ---- The video page -----------------------------------------------------------------------------------------

    /** The `<media-player>` with its captions and the overlays the player script drives (ids are how it finds them). */
    private fun playerMarkup(
        info: StreamInfo,
        serviceId: Int,
    ): String {
        val encodedUrl = WebUi.enc(info.url)
        val tracks =
            info.subtitles.orEmpty().joinToString("") { sub ->
                "      <track kind=\"captions\" src=\"/subtitles?serviceId=$serviceId&id=$encodedUrl&lang=${sub.languageTag}&auto=${sub.isAutoGenerated}\" " +
                    "srclang=\"${WebUi.esc(sub.languageTag)}\" label=\"${WebUi.esc(sub.displayLanguageName)}\">\n"
            }
        // Cover until the first frame; served same-origin because the player loads it in CORS mode (LocalHttpServerThumbnails.kt).
        val poster =
            sameOriginImageUrl(HtmlRendererCommon.getThumbnailUrl(info.thumbnails))
                ?.let { "    <media-poster class=\"vds-poster\" src=\"${WebUi.esc(it)}\" alt=\"\"></media-poster>\n" }
                .orEmpty()
        val layout =
            if (info.previewFrames.bestForSeekBar() != null) {
                "    <media-video-layout thumbnails=\"/thumbnails?serviceId=$serviceId&id=$encodedUrl\"></media-video-layout>\n"
            } else {
                "    <media-video-layout></media-video-layout>\n"
            }
        val danmaku = if (serviceSupportsBulletComments(serviceId)) "    <div class=\"danmaku-layer\" id=\"danmaku-layer\"></div>\n" else ""

        // .player-wrapper is the <media-player> itself; the mini-player logic moves it around.
        return "  <media-player id=\"player\" class=\"player-wrapper\" title=\"${WebUi.esc(info.name)}\" artist=\"${WebUi.esc(info.uploaderName)}\" " +
            "storage=\"fathom-player\" key-target=\"document\" crossorigin playsinline>\n" +
            "    <media-provider>\n$tracks    </media-provider>\n" +
            poster + layout + danmaku +
            "    <div class=\"double-tap-indicator left\" id=\"double-tap-left\">${WebUi.icon("fast_rewind")}<div class=\"double-tap-text\">-10s</div></div>\n" +
            "    <div class=\"double-tap-indicator right\" id=\"double-tap-right\">${WebUi.icon("fast_forward")}<div class=\"double-tap-text\">+10s</div></div>\n" +
            "    <div class=\"volume-hud\" id=\"volume-hud-indicator\"><span id=\"volume-hud-icon\" class=\"material-symbols-rounded\">volume_up</span><span id=\"volume-hud-text\">100%</span></div>\n" +
            "    <div class=\"up-next-overlay\" id=\"autoplay-overlay\">\n" +
            "      <div class=\"up-next-title\">Up Next</div>\n" +
            "      <div class=\"up-next-name\" id=\"autoplay-next-title\"></div>\n" +
            "      <img class=\"up-next-thumb\" id=\"autoplay-next-thumb\" src=\"\" alt=\"\">\n" +
            "      <div class=\"up-next-circle\"><svg width=\"56\" height=\"56\"><circle cx=\"28\" cy=\"28\" r=\"22\" class=\"up-next-circle-bg\"/><circle cx=\"28\" cy=\"28\" r=\"22\" class=\"up-next-circle-val\" id=\"autoplay-progress-circle\"/></svg></div>\n" +
            "      <div class=\"up-next-btn-row\"><button type=\"button\" class=\"up-next-btn up-next-btn-play\" id=\"autoplay-play-now\">Play Now</button><button type=\"button\" class=\"up-next-btn up-next-btn-cancel\" id=\"autoplay-cancel\">Cancel</button></div>\n" +
            "    </div>\n" +
            "    <button type=\"button\" class=\"sponsor-skip-btn\" id=\"sponsor-skip-btn\">${WebUi.icon("fast_forward")}<span id=\"sponsor-skip-label\"></span></button>\n" +
            "    <div class=\"mini-player-drag-handle\" id=\"mini-player-drag-handle\" title=\"Drag to move\">${WebUi.icon("open_with")}</div>\n" +
            "    <button type=\"button\" class=\"mini-player-close-btn\" id=\"mini-player-close-btn\" title=\"Close\">${WebUi.icon("close")}</button>\n" +
            "  </media-player>\n" +
            // Keeps the layout height when the player becomes a fixed mini-player, and the point whose scrolling out triggers it.
            "  <div id=\"player-space-holder\"></div>\n" +
            "  <div id=\"mini-player-sentinel\"></div>\n"
    }

    /** What js/player.js needs to know, as JSON: where the stream is, the video's chapters and SponsorBlock segments, what plays next. */
    private fun watchConfig(
        info: StreamInfo,
        serviceId: Int,
        duration: Long,
    ): String {
        val next = info.relatedItems.firstOrNull()
        val nextJson =
            if (next == null) {
                "null"
            } else {
                "{\"url\":${WebUi.jsonString("/watch?serviceId=$serviceId&id=${next.url}")},\"title\":${WebUi.jsonString(next.name)}," +
                    "\"thumb\":${WebUi.jsonString(HtmlRendererCommon.getThumbnailUrl(next.thumbnailUrl))}}"
            }

        // SponsorBlock reports milliseconds; the script wants seconds. Only skippable categories are asked for.
        val sponsor =
            SponsorBlockClient.fetchSegments(LocalHttpServer.getVideoId(info.url)).mapNotNull { seg ->
                val label =
                    when (seg.category) {
                        "sponsor" -> "sponsor"
                        "intro" -> "intro"
                        "outro" -> "outro"
                        "interaction" -> "reminder"
                        "selfpromo" -> "self-promotion"
                        "music_offtopic" -> "non-music part"
                        else -> null
                    }
                label?.let { "{\"s\":${seg.startMs / 1000.0},\"e\":${seg.endMs / 1000.0},\"c\":${WebUi.jsonString(seg.category)},\"l\":${WebUi.jsonString(it)}}" }
            }
        val chapters = info.streamSegments.orEmpty().joinToString(",") { "{\"s\":${it.startTimeSeconds},\"t\":${WebUi.jsonString(it.title)}}" }
        val danmaku =
            if (serviceSupportsBulletComments(serviceId)) "/danmaku?serviceId=$serviceId&id=${WebUi.enc(info.url)}" else ""

        return "{\"service\":$serviceId,\"title\":${WebUi.jsonString(info.name)},\"video\":${WebUi.jsonString(WebUi.enc(info.url))}," +
            "\"src\":${WebUi.jsonString("/manifest?serviceId=$serviceId&id=${WebUi.enc(info.url)}")},\"duration\":$duration,\"next\":$nextJson," +
            "\"sponsor\":[${sponsor.joinToString(",")}],\"chapters\":[$chapters],\"danmaku\":${WebUi.jsonString(danmaku)},\"download\":${serviceId == 0}}"
    }

    private fun chapterList(
        info: StreamInfo,
    ): String {
        val fallback = HtmlRendererCommon.getThumbnailUrl(info.thumbnails)
        val items =
            info.streamSegments.orEmpty().joinToString("") { chapter ->
                val thumb = HtmlRendererCommon.getThumbnailUrl(chapter.previewUrl?.takeIf { it.isNotBlank() } ?: fallback)
                // tabindex/role: a remote or the keyboard reaches each chapter like a button, and OK/Enter presses it.
                "<div class=\"chapter-item\" tabindex=\"0\" role=\"button\" data-action=\"seek-chapter\" data-seconds=\"${chapter.startTimeSeconds}\">" +
                    "<img class=\"chapter-thumb\" src=\"${WebUi.esc(thumb)}\" alt=\"\" loading=\"lazy\">" +
                    "<div class=\"chapter-item-body\"><span class=\"chapter-item-time\">${formatChapterTimestamp(chapter.startTimeSeconds)}</span>" +
                    "<span class=\"chapter-item-title\">${WebUi.esc(chapter.title)}</span></div></div>\n"
            }
        return "<div class=\"chapters-list\" id=\"chapters-list\">\n$items</div>\n"
    }

    /** The title, the uploader, and what can be done with the video. */
    private fun infoBlock(
        info: StreamInfo,
        serviceId: Int,
        isSubscribed: Boolean,
        isWatchLater: Boolean,
        likeState: String?,
    ): String {
        val avatarUrl = HtmlRendererCommon.getThumbnailUrl(info.uploaderAvatars)
        val subs = if (info.uploaderSubscriberCount >= 0) "${HtmlRendererCommon.formatCount(info.uploaderSubscriberCount)} subscribers" else ""
        val channelLink = "/channel?serviceId=$serviceId&id=${WebUi.enc(info.uploaderUrl)}"
        val videoBack = WebUi.enc("/watch?serviceId=$serviceId&id=${info.url}")
        val shareData = "data-action=\"share\" data-url=\"${WebUi.esc(info.url)}\" data-title=\"${WebUi.esc(info.name)}\""
        val audioLink = "/audio?serviceId=$serviceId&id=${WebUi.enc(info.url)}"
        // YouTube only: the downloader has no header handling for other CDNs. The script fills in the button's state.
        val download = if (serviceId == 0) "<button type=\"button\" id=\"download-btn\" class=\"btn\">${WebUi.icon("download")}Download</button>\n" else ""

        return "<section class=\"media-info\">\n" +
            "  <h1 class=\"media-title\">${WebUi.esc(info.name)}</h1>\n" +
            "  <div class=\"uploader-profile\">\n" +
            "    <div class=\"uploader-main\">\n" +
            "      <a href=\"$channelLink\" tabindex=\"-1\">${WebUi.avatar(info.uploaderName, avatarUrl)}</a>\n" +
            "      <div class=\"uploader-info\"><a class=\"uploader-name\" href=\"$channelLink\">${WebUi.esc(info.uploaderName)}</a><span class=\"uploader-subs\">${WebUi.esc(subs)}</span></div>\n" +
            "      ${WebUi.subscribeButton(info.uploaderUrl, info.uploaderName, avatarUrl, videoBack, isSubscribed)}" +
            "    </div>\n" +
            "    <div class=\"action-buttons-group\">\n" +
            WebUi.likeDislike(info, likeState) +
            WebUi.button("Pop-up", "picture_in_picture_alt", attrs = "data-action=\"popup\"") + "\n" +
            WebUi.button("Audio Only", "music_note", href = audioLink) + "\n" +
            WebUi.button("Share", "share", attrs = shareData) + "\n" +
            download +
            WebUi.watchLaterButton(info, serviceId, isWatchLater) +
            "    </div>\n" +
            "  </div>\n" +
            "</section>\n"
    }

    /**
     * The fragment for a video: everything under the page frame. It is injected into the page, and js/player.js then starts the player
     * from `#watch-config`. [duration] is the stream's length in seconds, which the seek bar trusts over the browser's guess.
     */
    @JvmStatic
    fun renderWatchContent(
        serviceId: Int,
        info: StreamInfo,
        isSubscribed: Boolean,
        isWatchLater: Boolean,
        likeState: String?,
        isTv: Boolean,
        duration: Long,
    ): String {
        val hasVideo = info.videoStreams.isNotEmpty() || info.videoOnlyStreams.isNotEmpty() || !info.hlsUrl.isNullOrEmpty()
        val chapters = if (hasVideo && !info.streamSegments.isNullOrEmpty()) chapterList(info) else ""
        val views = if (info.viewCount >= 0) "${HtmlRendererCommon.formatCount(info.viewCount)} views" else "Unknown views"
        val date = HtmlRendererCommon.formatUploadDate(info.uploadDate, info.textualUploadDate ?: "Unknown date")
        val encodedUrl = WebUi.enc(info.url)

        val sb = StringBuilder("<div class=\"watch\" data-title=\"${WebUi.esc(info.name)}\">\n<div class=\"watch-main\">\n")
        if (hasVideo) {
            sb.append(playerMarkup(info, serviceId))
              .append(if (serviceSupportsBulletComments(serviceId)) "  <div class=\"player-controls-row\"><button type=\"button\" class=\"danmaku-toggle-btn\" id=\"danmaku-toggle-btn\" title=\"Danmaku on/off\">${WebUi.icon("chat_bubble")}Danmaku</button></div>\n" else "")
        } else {
            // No video to play: show the cover, and offer the audio player instead.
            val cover = WebUi.esc(HtmlRendererCommon.getThumbnailUrl(info.thumbnails))
            sb.append("  <img class=\"audio-cover-still\" src=\"$cover\" alt=\"\">\n")
        }
        sb.append(infoBlock(info, serviceId, isSubscribed, isWatchLater, likeState))

        // Tabs. Related is a tab only on screens too narrow to show it beside the video (see watch.css).
        sb.append("<div class=\"watch-tabs\" role=\"tablist\">\n")
          .append("  <button type=\"button\" class=\"watch-tab active\" role=\"tab\" data-panel=\"about\">About</button>\n")
        if (chapters.isNotEmpty()) sb.append("  <button type=\"button\" class=\"watch-tab\" role=\"tab\" data-panel=\"chapters\">Chapters</button>\n")
        sb.append("  <button type=\"button\" class=\"watch-tab\" role=\"tab\" data-panel=\"comments\">Comments</button>\n")
          .append("  <button type=\"button\" class=\"watch-tab\" role=\"tab\" data-panel=\"related\">Related</button>\n")
          .append("</div>\n")

        // No whitespace between tags and text in the description: its box is white-space:pre-wrap.
        sb.append("<div class=\"tab-panel active\" data-panel=\"about\"><div class=\"media-description\"><div class=\"media-stats\">${WebUi.esc(views)} • ${WebUi.esc(date)}</div>${descriptionHtml(info)}</div></div>\n")
        if (chapters.isNotEmpty()) sb.append("<div class=\"tab-panel\" data-panel=\"chapters\">\n$chapters</div>\n")
        sb.append("<div class=\"tab-panel comments-section\" data-panel=\"comments\">\n")
          .append(WebUi.asyncRegion("/comments?serviceId=$serviceId&id=$encodedUrl", "Loading comments..."))
          .append("</div>\n</div>\n")

        sb.append("<aside class=\"watch-related tab-panel\" data-panel=\"related\">\n<h2 class=\"watch-related-title\">Related</h2>\n")
          .append(relatedList(info, serviceId, "/watch"))
          .append("</aside>\n</div>\n")
        if (hasVideo) sb.append(WebUi.jsonData("watch-config", watchConfig(info, serviceId, duration)))
        return sb.toString()
    }

    // ---- The audio page -----------------------------------------------------------------------------------------

    @JvmStatic
    fun renderAudioWatch(
        serviceId: Int,
        info: StreamInfo,
        isSubscribed: Boolean,
        isWatchLater: Boolean,
        likeState: String?,
        isTv: Boolean,
    ): String {
        val views = if (info.viewCount >= 0) "${HtmlRendererCommon.formatCount(info.viewCount)} views" else "Unknown views"
        val date = HtmlRendererCommon.formatUploadDate(info.uploadDate, info.textualUploadDate ?: "Unknown date")
        val encodedUrl = WebUi.enc(info.url)
        val poster = HtmlRendererCommon.getThumbnailUrl(info.thumbnails)
        val avatarUrl = HtmlRendererCommon.getThumbnailUrl(info.uploaderAvatars)
        val audioBack = WebUi.enc("/audio?serviceId=$serviceId&id=${info.url}")
        val mime = info.audioStreams.orEmpty().firstOrNull()?.format?.mimeType ?: "audio/mpeg"
        val channelLink = "/channel?serviceId=$serviceId&id=${WebUi.enc(info.uploaderUrl)}"

        val config =
            "{\"title\":${WebUi.jsonString(info.name)},\"artist\":${WebUi.jsonString(info.uploaderName)}," +
                "\"src\":${WebUi.jsonString("/stream?serviceId=$serviceId&id=$encodedUrl")},\"mime\":${WebUi.jsonString(mime)}," +
                "\"poster\":${WebUi.jsonString(sameOriginImageUrl(poster).orEmpty())}}"

        val sb = StringBuilder(WebShell.header(serviceId, "", "audio"))
        sb.append("<main class=\"container\">\n<div class=\"watch\">\n<div class=\"watch-main\">\n")
          .append("<section class=\"audio-card\">\n")
          .append("  <div class=\"audio-cover\"><img id=\"audio-cover\" src=\"${WebUi.esc(poster)}\" alt=\"\"><span class=\"audio-badge\">${WebUi.icon("music_note")}Audio Only</span></div>\n")
          .append("  <h1 class=\"media-title\">${WebUi.esc(info.name)}</h1>\n")
          .append("  <a class=\"audio-artist\" href=\"$channelLink\">${WebUi.esc(info.uploaderName)}</a>\n")
          // The Vidstack audio layout. The element keeps id="audio-player" and the media API the app's native-audio sync uses.
          .append("  <media-player id=\"audio-player\" class=\"audio-player\" view-type=\"audio\" title=\"${WebUi.esc(info.name)}\" artist=\"${WebUi.esc(info.uploaderName)}\" storage=\"fathom-player\" key-target=\"document\" crossorigin playsinline>\n")
          .append("    <media-provider></media-provider>\n    <media-audio-layout></media-audio-layout>\n  </media-player>\n")
          .append("  <div class=\"action-buttons-group audio-actions\">\n")
          .append(WebUi.button("Video Mode", "tv", "filled", href = "/watch?serviceId=$serviceId&id=$encodedUrl&force_video=true"))
          .append(WebUi.likeDislike(info, likeState, includeDislike = false))
          .append(WebUi.subscribeButton(info.uploaderUrl, info.uploaderName, avatarUrl, audioBack, isSubscribed))
          .append(WebUi.watchLaterButton(info, serviceId, isWatchLater))
          .append("  </div>\n</section>\n")
          .append("<div class=\"media-description\"><div class=\"media-stats\">${WebUi.esc(views)} • ${WebUi.esc(date)}</div>${descriptionHtml(info)}</div>\n")
          .append("</div>\n<aside class=\"watch-related\">\n<h2 class=\"watch-related-title\">Up Next</h2>\n")
          .append(relatedList(info, serviceId, "/audio"))
          .append("</aside>\n</div>\n</main>\n")
          .append(WebUi.jsonData("audio-config", config))
        return WebShell.page("Audio: ${info.name}", sb.toString(), isTv, needsPlayer = true)
    }

    // ---- Comments -----------------------------------------------------------------------------------------------

    /**
     * A page of comments, or of replies: a fragment that is injected. It ends with its own "load more" (which the next page replaces),
     * so a thread can be extended as far as the server has pages.
     */
    @JvmStatic
    fun renderComments(
        serviceId: Int,
        videoUrl: String,
        items: List<CommentsInfoItem>,
        nextPage: Page?,
        isTv: Boolean,
        isReplies: Boolean = false,
    ): String {
        val base = "/comments?serviceId=$serviceId&id=${WebUi.enc(videoUrl)}"
        val context = if (isReplies) "&context=replies" else ""
        val sb = StringBuilder()
        if (items.isEmpty()) sb.append(WebUi.notice("No comments yet."))

        for (item in items) {
            val author = item.uploaderName.orEmpty()
            val avatarUrl = item.uploaderAvatarUrl?.takeIf { HtmlRendererCommon.hasThumbnail(it) }
            val time = HtmlRendererCommon.formatUploadDate(item.uploadDate, item.textualUploadDate ?: "")
            val likes = if (item.likeCount > 0) HtmlRendererCommon.formatCount(item.likeCount.toLong()) else ""
            val verified = if (item.isUploaderVerified) "<span class=\"material-symbols-rounded comment-verified\" title=\"Verified\">check_circle</span>" else ""

            sb.append("<div class=\"comment\">\n")
              .append("  ${WebUi.avatar(author, avatarUrl, "sm")}\n")
              .append("  <div class=\"comment-details\">\n")
              .append("    <div class=\"comment-header\"><span class=\"comment-author\">${WebUi.esc(author)}$verified</span><span class=\"comment-time\">${WebUi.esc(time)}</span></div>\n")
            if (item.isPinned) sb.append("    <div class=\"comment-pinned\">${WebUi.icon("push_pin")}Pinned</div>\n")
            // Description.content is HTML from the extractor, and is rendered as it is.
            sb.append("    <div class=\"comment-text\">${item.commentText.content.orEmpty()}</div>\n")
            if (likes.isNotEmpty() || item.isHeartedByUploader) {
                sb.append("    <div class=\"comment-meta\">")
                if (likes.isNotEmpty()) sb.append("<span class=\"comment-like\">${WebUi.icon("thumb_up")}${WebUi.esc(likes)}</span>")
                if (item.isHeartedByUploader) sb.append("<span class=\"comment-hearted\" title=\"Hearted by creator\">${WebUi.icon("favorite")}</span>")
                sb.append("</div>\n")
            }
            val replies = item.replies
            if (item.replyCount > 0 && replies != null) {
                HtmlRendererCommon.serializePage(replies)?.let { token ->
                    sb.append("    <button type=\"button\" class=\"comment-replies-toggle\" data-action=\"toggle-replies\" data-url=\"${WebUi.esc("$base&nextPage=${WebUi.enc(token)}&context=replies")}\">")
                      .append("<span class=\"material-symbols-rounded reply-chevron\">expand_more</span>${item.replyCount} replies</button>\n")
                      .append("    <div class=\"comment-replies\"></div>\n")
                }
            }
            sb.append("  </div>\n</div>\n")
        }

        val next = HtmlRendererCommon.serializePage(nextPage)?.let { "$base&nextPage=${WebUi.enc(it)}$context" }
        sb.append(WebUi.loadMore(next, if (isReplies) "Load more replies" else "Load more comments"))
        return sb.toString()
    }
}
