package io.github.aedev.flow.player.stream

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import org.schabi.newpipe.extractor.MediaFormat

/** The player boundary: a caption must reach the player as the same stream it used to be built as. */
class ResolvedCaptionTest {
    @Test
    fun `an authored srv3 caption becomes a transcript3 stream with the same url and language`() {
        val url = "https://www.youtube.com/api/timedtext?v=x&lang=en&fmt=srv3"
        val stream = ResolvedCaption("en", isAutoGenerated = false, url = url, format = CaptionFormat.SRV3).toSubtitlesStream()!!

        assertEquals(url, stream.content)
        assertEquals(MediaFormat.TRANSCRIPT3, stream.format)
        assertEquals("en", stream.languageTag)
        assertFalse(stream.isAutoGenerated)
        assertFalse(CaptionTrackResolver.isTranslated(stream))
    }

    @Test
    fun `a translated vtt caption stays translated and auto generated as a stream`() {
        val caption =
            ResolvedCaption(
                languageTag = "es",
                isAutoGenerated = true,
                url = "https://www.youtube.com/api/timedtext?v=x&lang=en&fmt=vtt&tlang=es",
                format = CaptionFormat.VTT,
            )
        val stream = listOf(caption).toSubtitlesStreams().single()

        assertTrue(caption.isTranslated)
        assertTrue(CaptionTrackResolver.isTranslated(stream))
        assertEquals(MediaFormat.VTT, stream.format)
        assertTrue(stream.isAutoGenerated)
    }
}
